# Netlify configuration

[build]
  publish = "."

# Sitemap generation plugin
[[plugins]]
  package = "@netlify/plugin-sitemap"

# Sitemap submission plugin
[[plugins]]
  package = "netlify-plugin-submit-sitemap"

# Explicitly disable netlify-plugin-image-optim due to a bug in v0.4.0
# causing "Cannot set properties of undefined (setting 'post')" errors.
# This overrides the UI-installed plugin.
# See: https://github.com/chrisdwheatley/netlify-plugin-image-optim/issues
[[plugins]]
  package = "netlify-plugin-image-optim"
  enabled = false
